AWSTemplateFormatVersion: 2010-09-09
Description: 6Sense EKS environment
Parameters:
  
  # for github actions
  GitHubOrg:
    Description: Name of GitHub organization/user (case sensitive)
    Type: String
  # RepositoryName:
  #   Description: Name of GitHub repository (case sensitive)
  #   Type: String
  #   Default: "6Sense"
  OIDCProviderArn:
    Description: Arn for the GitHub OIDC Provider. leave empty
    Default: ""
    Type: String
  OIDCAudience:
    Description: Audience supplied to configure-aws-credentials.
    Default: "sts.amazonaws.com"
    Type: String


Conditions:
  CreateOIDCProvider: !Equals 
    - !Ref OIDCProviderArn
    - ""

Resources:
  
###################### github actions role #############################
  GitHubActionsRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Action: sts:AssumeRoleWithWebIdentity
              Principal:
                Federated: !If 
                  - CreateOIDCProvider
                  - !Ref GithubOidc
                  - !Ref OIDCProviderArn
              Condition:
                StringEquals:
                  token.actions.githubusercontent.com:aud: !Ref OIDCAudience
                StringLike:
                  token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/*:*
        Policies:
          - PolicyName: ECRFullAccessPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - ecr:*
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - "ssm:GetParameter"
                    - "ssm:GetParameters"
                    - "ssm:GetParametersByPath"
                  Resource: '*'
  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Condition: CreateOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList:
        - ffffffffffffffffffffffffffffffffffffffff


#####################  ECR Repository ###########################
# MyRepository: 
#   Type: AWS::ECR::Repository
#   Properties: 
#     RepositoryName: !Ref RepositoryName
    

Outputs:
  GitHubActionsRoleARN:
    Value: !GetAtt GitHubActionsRole.Arn 
  