apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-argocd
  namespace: argocd
  annotations:
    # cert-manager.io/issuer: letsencrypt-nginx
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  # tls:
  #   - hosts:
  #     - argocd.6senseev.com
  #     secretName: letsencrypt-nginx-quote
  rules:  
    - host: argocd.6senseev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: https
  ingressClassName: nginx