apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: backend
spec:
  selector: 
    app: myapp 
  ports:
  - name: http
    port: 80
    # protocol: TCP
    targetPort: 8080
  

---
apiVersion: v1
kind: Service
metadata:
  name: quote
  namespace: backend
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: quote
