apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 6sense-ev-ocpp-server
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: backend
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'git@github.com:6senseEV/k8s-deployments.git'
    path: beta/6sense-ev-ocpp-server
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true